export const specializationOptions = [
  { value: 'family_medicine', label: 'طب الأسرة' },
  { value: 'pediatrics', label: 'طب الأطفال' },
  { value: 'obstetrics_and_gynecology', label: 'النساء والتوليد' },
  { value: 'cardiology', label: 'أمراض القلب' },
  { value: 'dermatology', label: 'الأمراض الجلدية' },
  { value: 'neurology', label: 'الأعصاب' },
  { value: 'orthopedics', label: 'جراحة العظام' },
  { value: 'ophthalmology', label: 'العيون' },
  { value: 'ent', label: 'الأنف والأذن والحنجرة' },
  { value: 'dentistry', label: 'طب الأسنان' },
  { value: 'oncology', label: 'الأورام' },
  { value: 'gastroenterology', label: 'الجهاز الهضمي' },
  { value: 'psychiatry', label: 'الطب النفسي' },
  { value: 'urology', label: 'المسالك البولية' },
  { value: 'endocrinology', label: 'الغدد الصماء' },
  { value: 'rheumatology', label: 'الروماتيزم' },
  { value: 'anesthesiology', label: 'التخدير' },
  { value: 'emergency_medicine', label: 'الطوارئ' },
  { value: 'radiology', label: 'الأشعة' },
  { value: 'nuclear_medicine', label: 'الطب النووي' },
];